name: Build OpenMRS Distro Bahmni

on:
  push:
    branches:
      - master
      - 'BAH-*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Create maven settings.xml
      run: |
        cat <<EOT >> settings.xml
        <settings>
          <servers>
            <server>
              <id>1-bahmni-core</id>
              <username>${username}</username>
              <password>${password}</password>
            </server>
          </servers>
        </settings>
        EOT

    - name: Build with Maven
      run: |
       ./mvnw -B --settings ./settings.xml \
       clean install
       -Dusername=$USERNAME \
        -Dpassword=$PASSWORD
     
    - name: Upload artifacts 
      uses: actions/upload-artifact@v2
      with:
          name: Bahmnicore
          path: distro/target/distro-0.94-SNAPSHOT-distro.zip
        
